/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pastpaper2023examo2;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class Question2GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Question2GUI.class.getName());

    /**
     * Creates new form Question2GUI
     */
    public Question2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        eatateAgentNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        propertyPriceField = new javax.swing.JTextField();
        comissionPercentageField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ExitMenuOption = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ProcessReportMenuOption = new javax.swing.JMenuItem();
        ClearMenuOption = new javax.swing.JMenuItem();
        SaveReportMenuOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("AGENT LOCATION : ");

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Pretoria" }));

        jLabel2.setText("ESTATE AGENT NAME : ");

        jLabel3.setText("PROPERTY PRICE : ");

        jLabel4.setText("COMISSION PERCENTAGE :");

        jLabel5.setText("ESTATE AGENT REPORT :");

        reportTextArea.setEditable(false);
        reportTextArea.setColumns(20);
        reportTextArea.setRows(5);
        jScrollPane1.setViewportView(reportTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(comissionPercentageField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(propertyPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eatateAgentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eatateAgentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(propertyPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(comissionPercentageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        ExitMenuOption.setText("Exit");
        ExitMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuOptionActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenuOption);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        ProcessReportMenuOption.setText("Process Report");
        ProcessReportMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessReportMenuOptionActionPerformed(evt);
            }
        });
        jMenu2.add(ProcessReportMenuOption);

        ClearMenuOption.setText("Clear");
        ClearMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMenuOptionActionPerformed(evt);
            }
        });
        jMenu2.add(ClearMenuOption);

        SaveReportMenuOption.setText("Save Report");
        SaveReportMenuOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveReportMenuOptionActionPerformed(evt);
            }
        });
        jMenu2.add(SaveReportMenuOption);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuOptionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitMenuOptionActionPerformed

    private void ClearMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMenuOptionActionPerformed
      locationComboBox.setSelectedIndex(0);
      eatateAgentNameField.setText("");
      propertyPriceField.setText("");
      comissionPercentageField.setText("");
      reportTextArea.setText("");
       
    }//GEN-LAST:event_ClearMenuOptionActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
      locationComboBox.setSelectedIndex(0);
      eatateAgentNameField.setText("");
      propertyPriceField.setText("");
      comissionPercentageField.setText("");
      reportTextArea.setText("");
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void ProcessReportMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessReportMenuOptionActionPerformed
        String location = (String) locationComboBox.getSelectedItem();
        String name = eatateAgentNameField.getText();
        String propertyPrice = propertyPriceField.getText();
        String commission = comissionPercentageField.getText();
        
        Data data = new Data(location, name, propertyPrice, commission);
        PastPaper2023ExamO2 ppe = new PastPaper2023ExamO2();
        
        boolean isValidData = ppe.ValidateData(data);
        
        if ( isValidData ) {
            String report = ppe.getReport(data);
            
            reportTextArea.setText(report);
        }
        
    }//GEN-LAST:event_ProcessReportMenuOptionActionPerformed

    private void SaveReportMenuOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveReportMenuOptionActionPerformed
        //Writing to file
        
        String location = (String) locationComboBox.getSelectedItem();
        String name = eatateAgentNameField.getText();
        String propertyPrice = propertyPriceField.getText();
        String commission = comissionPercentageField.getText();

        Data data = new Data(location, name, propertyPrice, commission);
        PastPaper2023ExamO2 ppe = new PastPaper2023ExamO2();
        
        String report = ppe.getReport(data);
        
        BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new FileWriter ("report.txt"));

            writer.write(report);
        }
        catch(IOException e ) {
            JOptionPane.showMessageDialog(this, "Issue writing to file","Save Error", JOptionPane.ERROR_MESSAGE);
        }
        finally {
            try {
                writer.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Issue close text file","Save Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SaveReportMenuOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Question2GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClearMenuOption;
    private javax.swing.JMenuItem ExitMenuOption;
    private javax.swing.JMenuItem ProcessReportMenuOption;
    private javax.swing.JMenuItem SaveReportMenuOption;
    private javax.swing.JTextField comissionPercentageField;
    private javax.swing.JTextField eatateAgentNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JTextField propertyPriceField;
    private javax.swing.JTextArea reportTextArea;
    // End of variables declaration//GEN-END:variables
}
